
- name: Create "{{deploy.local.dev}}"  directory if it does not exist
  file:
    path: "{{deploy.local.dev}}"
    state: directory
    mode: '0755'

- name: Directory ownership to "{{deploy.user.name}}"
  file:
    path: "{{deploy.local.dev}}"
    state: directory
    recurse: yes
    owner: "{{deploy.user.name}}"
    group: "{{deploy.user.group}}"

- name: Check-out from Git
  git:
    repo: "{{remote.repo.url}}"
    dest: "{{deploy.local.dev}}/{{deploy.app.name}}"
  become_user: "{{deploy.user.name}}"

