---

- hosts: app_servers
  become: yes
  roles: 
    - {
        role: common,
        tags: ['common']
        }
    - {
        role: mongodb,
        tags: ['mongodb']
        }
    - {
        role: nginxinc.nginx,
        tags: ['nginx']
    }
    - {
        role: geerlingguy.supervisor,
        tags: ['supervisor', 'supervisord']
    }
    - {
        role: apps.vagrant-django,
        tags: ['vagrant-django']
    }

    # - common
    # - mongodb

    # - django