---

- hosts: app_servers
  become: yes
  roles: 
    - {
        role: common,
        tags: ['common']
        }
    - {
        role: mongodb,
        tags: ['mongodb']
        }

    # - common
    # - mongodb

    # - django